before_script:
  - npm install
before_install:
  - wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu52_52.1-3ubuntu0.4_amd64.deb
  - sudo dpkg -i libicu52_52*.deb
language: node_js
node_js:
  - "6.0"
script:
  - npm test
after_script:
  - npm run list2
  - npm run list
  - npm run coveralls